global:
  resolve_timeout: 5m
  smtp_from: alertmanager@icerink.com
  smtp_smarthost: smtp.icerink.com:587
  smtp_auth_username: alertmanager
  smtp_auth_password: '{{ SMTP_PASSWORD }}'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: team-emails
  routes:
    - match:
        severity: critical
      receiver: team-pager

receivers:
  - name: team-emails
    email_configs:
      - to: team@icerink.com

  - name: team-pager
    email_configs:
      - to: team-pager@icerink.com
    slack_configs:
      - channel: '#alerts'
        api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ['alertname', 'cluster', 'service']

# Human Tasks:
# 1. Set up SMTP server for sending email alerts (Required)
# 2. Configure Slack webhook for critical alerts (Required)
# 3. Review and adjust alert routing rules based on team structure and preferences (Required)
# 4. Ensure sensitive information (SMTP password, Slack API URL) is stored securely and not in plain text in this file (Critical)