apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: ice-rink-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ice-rink-api
  template:
    metadata:
      labels:
        app: ice-rink-api
    spec:
      containers:
      - name: ice-rink-api
        image: {{ ECR_REGISTRY }}/ice-rink-api:{{ IMAGE_TAG }}
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: redis-url
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

# Human tasks:
# - Replace {{ ECR_REGISTRY }} with the actual Amazon ECR registry URL
# - Replace {{ IMAGE_TAG }} with the appropriate image tag or version
# - Review and adjust resource limits and requests based on actual application requirements
# - Ensure the secrets 'api-secrets' are created with the correct keys (database-url, redis-url)
# - Verify the health check endpoints (/health and /ready) are implemented in the API